services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"

  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5002:5002"
    depends_on:
      - backend
      - users-service


      